services:
  - type: web
    name: ticketcolombia-frontend
    env: node
    buildCommand: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/render/flutter
      export PATH="/opt/render/flutter/bin:$PATH"
      flutter config --no-analytics
      flutter precache --web
      flutter build web --release
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
